//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.03 at 10:00:30 PM SGT 
//


package cs.a_ement_soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
public class Paksa {

    protected String name;
    protected String subjectCode;
    protected String description;
    protected int units;
    protected int status;


    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getSubjectCode() {
        return subjectCode;
    }

    public void setSubjectCode(String value) {
        this.subjectCode = value;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        this.description = value;
    }

    public int getUnits() {
        return units;
    }

    public void setUnits(int value) {
        this.units = value;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int value) {
        this.status = value;
    }

}
